//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANUFACTURER
    {
        public int IDMANUFACTURER { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> SPECIFICATIONSID { get; set; }
        public Nullable<int> CONSIGMENTID { get; set; }
    
        public virtual CONSIGNMENT CONSIGNMENT { get; set; }
        public virtual SPECIFICATIONS SPECIFICATIONS { get; set; }
    }
}
