//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMPUTEREntities : DbContext
    {
        public COMPUTEREntities()
            : base("name=COMPUTEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONSIGNMENT> CONSIGNMENT { get; set; }
        public virtual DbSet<DISTRIBUTOR> DISTRIBUTOR { get; set; }
        public virtual DbSet<MANUFACTURER> MANUFACTURER { get; set; }
        public virtual DbSet<SPECIFICATIONS> SPECIFICATIONS { get; set; }
    }
}
