//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIFICATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPECIFICATIONS()
        {
            this.MANUFACTURER = new HashSet<MANUFACTURER>();
        }
    
        public int MANUFACTURERID { get; set; }
        public string MODEL { get; set; }
        public string CPU { get; set; }
        public int FREQUENCY { get; set; }
        public int RAM { get; set; }
        public int HardDiskSpace { get; set; }
        public System.DateTime RELEASEdATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURER> MANUFACTURER { get; set; }
    }
}
